apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streaming-backend
  template:
    metadata:
      labels:
        app: streaming-backend
    spec:
      containers:
        - name: server
          image: yourrepo/streaming-backend:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-backend
spec:
  selector:
    app: streaming-backend
  ports:
    - port: 80
      targetPort: 8080
